#!/bin/bash

CONFIG_FILE="config.yaml"

echo "POSTGRES_USER=$(yq eval '.POSTGRES_SETTINGS.USERNAME' $CONFIG_FILE)" >> .env
echo "POSTGRES_PASSWORD=$(yq eval '.POSTGRES_SETTINGS.PASSWORD' $CONFIG_FILE)" >> .env
echo "POSTGRES_DB=$(yq eval '.POSTGRES_SETTINGS.DB_NAME' $CONFIG_FILE)" >> .env
echo "POSTGRES_SCHEMA=$(yq eval '.POSTGRES_SETTINGS.SCHEMA' $CONFIG_FILE)" >> .env
echo "POSTGRES_HOST=$(yq eval '.POSTGRES_SETTINGS.HOST' $CONFIG_FILE)" >> .env
echo "POSTGRES_PORT=$(yq eval '.POSTGRES_SETTINGS.PORT' $CONFIG_FILE)" >> .env