APP_NAME: cinerate-api
API_VERSION: 1
POSTGRES_SETTINGS:
  USERNAME: test
  PASSWORD: test
  DB_NAME: test
  SCHEMA: public
  HOST: db
  PORT: 5432
EXTERNAL_API_SETTINGS:
  API_BASE_URL: https://api.kinopoisk.dev/v1.4
  API_ACCESS_TOKEN: XXXXXXX-XXXXXXX-XXXXXXX-XXXXXXX
SECURITY_SETTINGS:
  SECRET_KEY: supersecretkey
  ACCESS_TOKEN_EXPIRE_MINUTES: 1
ADMIN_USER:
  login: admin
  password: admin